import type { Value } from 'platejs';

// Document Discussion Types - matching Plate.js discussion kit
export interface DocumentDiscussion {
    id: string;
    comments: DocumentComment[];
    createdAt: Date;
    isResolved: boolean;
    userId: string;
    documentContent?: string;
}

export interface DocumentComment {
    id: string;
    contentRich: Value; // Plate.js rich content
    createdAt: Date;
    discussionId: string;
    isEdited: boolean;
    userId: string;
}

// Database model types (generated by Prisma)
export type { Document, DocumentDiscussion as PrismaDocumentDiscussion, DocumentComment as PrismaDocumentComment } from '@prisma/client';
